LoadImaged:
  keys: ["image"]

EnsureChannelFirstd:
  keys: ["image"]

Orientationd:
  keys: ["image"]
  axcodes: "RAS"

Spacingd:
  keys: ["image"]
  pixdim: [1.5, 1.5, 2.0]
  mode: ["bilinear", "nearest"]

ScaleIntensityRanged:
  keys: ["image"]
  a_min: -175
  a_max: 250
  b_min: 0.0
  b_max: 1.0
  clip: True

CropForegroundd:
  keys: ["image"]
  source_key: "image"
