LoadImaged:
  keys: ["image", "label"]

EnsureChannelFirstd:
  keys: ["image", "label"]

Orientationd:
  keys: ["image", "label"]
  axcodes: "RAS"

Spacingd:
  keys: ["image", "label"]
  pixdim: [1.5, 1.5, 2.0]
  mode: ["bilinear", "nearest"]

ScaleIntensityRanged:
  keys: ["image"]
  a_min: -175
  a_max: 250
  b_min: 0.0
  b_max: 1.0
  clip: True

CropForegroundd:
  keys: ["image", "label"]
  source_key: "image"

RandCropByPosNegLabeld:
  keys: ["image", "label"]
  label_key: "label"
  spatial_size: [96, 96, 96]
  pos: 1
  neg: 1
  num_samples: 4
  image_key: "image"
  image_threshold: 0

RandFlipd:
  keys: ["image", "label"]
  spatial_axis: [0]
  prob: 0.10

RandFlipd:
  keys: ["image", "label"]
  spatial_axis: [1]
  prob: 0.10

RandFlipd:
  keys: ["image", "label"]
  spatial_axis: [2]
  prob: 0.10

RandRotate90d:
  keys: ["image", "label"]
  prob: 0.10
  max_k: 3

RandShiftIntensityd:
  keys: ["image"]
  offsets: 0.10
  prob: 0.50
