LoadImaged:
  keys: ["image", "label"]

EnsureChannelFirstd:
  keys: ["label"]

Orientationd:
  keys: ["image", "label"]
  axcodes: "RAS"

Spacingd:
  keys: ["image", "label"]
  pixdim: [1.0, 1.0, 1.0]
  mode: ["bilinear", "nearest"]

ScaleIntensityRanged:
  keys: ["image"]
  a_min: 0.0
  a_max: 1.0
  b_min: 0.0
  b_max: 1.0
  clip: True

CropForegroundd:
  keys: ["image", "label"]
  source_key: "image"
