model: UNETR
args:
  in_channels: 1
  out_channels: 14
  img_size: [96, 96, 96]
  feature_size: 16
  hidden_size: 768
  mlp_dim: 3072
  num_heads: 12
  pos_embed: "perceptron"
  norm_name: "instance"
  res_block: True
  dropout_rate: 0.0
