model: SwinUNETR

args:
  img_size: [96, 96, 96]
  in_channels: 5
  out_channels: 3
  feature_size: 48

weights:
  path: ckpt_vessels/vessels_swin_unetr_48_pretrained.pt
  remap_keys:
    - ['swinViT.', 'linear']
    - ['module.', 'fc']

training:
  lr: 0.0001
  weight_decay: 0.00001